sudo: required
language: node_js
services: docker
install: npm install
before_script:
  - docker pull rabbitmq:3-management-alpine
  - docker run --name rabbitmq -d -p 5672:5672 rabbitmq:3-management-alpine
script: npm test
