sudo: required
language: node_js
node_js:
 - "8"
services: docker
install: npm install
before_script:
  - docker pull rabbitmq:3-alpine
  - docker run --name rabbitmq -d -p 5672:5672 rabbitmq:3-alpine
  - sleep 10
script: npm test
