sudo: required
language: node_js
node_js:
 - "8"
services: docker
install: npm install
before_script:
  - docker pull rabbitmq:3-management-alpine
  - docker run --name rabbitmq -d -p 5672:5672 -p 15672:15672 rabbitmq:3-management-alpine
  - until $(curl --output /dev/null --silent --head --fail http://localhost:15672); do printf '.'; sleep 2; done
script: npm test
